name: Continuous Integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install explainaboard
          pip install .
          python -c "import nltk; nltk.download('omw-1.4')"
      - name: Run tests with unittest
        run: python -m unittest discover

    format:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install Python 3
          uses: actions/setup-python@v3
          with:
            python-version: 3.9
        - name: format
          uses: pre-commit/action@v2.0.3
          with:
            extra_args: black --all-files
            exclude: "datasets"
      isort:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Install Python 3
            uses: actions/setup-python@v3
            with:
              python-version: 3.9
          - name: isort
            uses: pre-commit/action@v2.0.3
            with:
              extra_args: isort --all-files
              exclude: "datasets"
      lint:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Install Python 3
            uses: actions/setup-python@v3
            with:
              python-version: 3.9
          - name: lint
            uses: pre-commit/action@v2.0.3
            with:
              extra_args: flake8 --all-files
              exclude: "datasets"
